# Workflow -> Triggers -> Job(s) -> runner -> Step(s) -> Result

name : Laptop-GCP   # workflow name

on:
  push:
    branches: [main]  # trigger the workflow



jobs:   # jobs 1 : Testing CI
  build:
    runs-on: ubuntu-latest   # runner
    steps:

      - name: checkout repo content # -> checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Python # -> download python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install requirements  # ->install requirements
        run: pip install -r requirements.txt

      - name: Docker build   # -> docker build
        run: docker build -t laptop-mlops-gcp .
      
      - name: save docker image
        run: docker save laptop-mlops-gcp > image.tar
      
      - name : upload docker image to artifact
        uses : actions/upload-artifact@v4
        with:
          name : docker-image
          path: image.tar

    deploy:
      need: build
      runs-on: ubuntu-latest   # runner
      
      enviorment: production
      steps:
        - name: checkout repo content # -> checkout repo
          uses: actions/checkout@2
        
        - name: load docker  # -> load the saved image
          run: docker load < image.tar

        - name: Authenticate gcp   # -> load gcp credentials
          uses: google-github-actions/auth@v2
          with: 
            credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        
        - name: Set GCP project   # -> load gcp project id
          run: gcloud config set project ${{ secrets.project_id }}
        
        - name: push docker image to artifacts registry  # -> push our docker image to gcp artifacts
          run:
            docker tag laptop-mlops-app gcr.io/${{ secrets.GCP_PROJECT_ID }}/laptop-mlops-gcp
            docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/laptop-mlops-gcp
        
        - name: deploy Docker image in gcp   # ->  deploy our docker to cloud run
          run :
            gcloud run deploy laptop-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/laptopmlopsgcp \
            --region asia-south1 \
            --platform managed \
            --allow-unauthenticated